export class Category {
  constructor(
    public readonly id: string,
    public readonly name: string,
    public readonly slug: string,
    public readonly description?: string,
    public readonly color?: string,
    public readonly icon?: string,
    public readonly isActive: boolean = true,
    public readonly sortOrder: number = 0,
    public readonly createdAt: Date = new Date(),
    public readonly updatedAt: Date = new Date()
  ) {}

  public isAvailableForPosts(): boolean {
    return this.isActive;
  }

  public static create(data: {
    name: string;
    slug: string;
    description?: string;
    color?: string;
    icon?: string;
    sortOrder?: number;
  }): Category {
    return new Category(
      '', // ID will be generated by database
      data.name,
      data.slug,
      data.description,
      data.color,
      data.icon,
      true,
      data.sortOrder || 0
    );
  }
}