import { UserRole } from "../enums/UserRole";

export class User {
  constructor(
    public readonly id: string,
    public readonly email: string,
    public readonly username: string,
    public readonly firstName: string,
    public readonly lastName: string,
    public readonly password: string,
    public readonly avatar?: string,
    public readonly bio?: string,
    public readonly role: UserRole = UserRole.USER,
    public readonly isActive: boolean = true,
    public readonly createdAt: Date = new Date(),
    public readonly updatedAt: Date = new Date()
  ) {}

  public getFullName(): string {
    return `${this.firstName} ${this.lastName}`;
  }

  public isAdmin(): boolean {
    return this.role === UserRole.ADMIN;
  }

  public isAuthor(): boolean {
    return this.role === UserRole.AUTHOR || this.role === UserRole.ADMIN;
  }

  public canWrite(): boolean {
    return this.isAuthor() && this.isActive;
  }

  public static create(data: {
    email: string;
    username: string;
    firstName: string;
    lastName: string;
    password: string;
    avatar?: string;
    bio?: string;
    role?: UserRole;
  }): User {
    return new User(
      '', // ID will be generated by database
      data.email,
      data.username,
      data.firstName,
      data.lastName,
      data.password,
      data.avatar,
      data.bio,
      data.role || UserRole.USER
    );
  }
}